language: python

python:
    - "2.7"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

# Install dependencies
install: 
  - pip install -r requirements.txt

# Run tests
script:
  - python RaspberryPi/src/test_unit_runner.py

# notify slack
notifications:
  slack: sdpteam5:Phj2pEgAtOIqSsJ9hST7F1qD
