language: python

python:
    - "2.7"

# install dependencies
install: 
  - pip install -r requirements.txt

# check style
script:
  - find . -iname "*.py" | xargs pylint

# notify slack
notifications:
  slack: sdpteam5:Phj2pEgAtOIqSsJ9hST7F1qD
